### ISSUE TITLE
Success Criterion 1.2.1 - Audio-only and Video-only (Prerecorded) - Level A

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#17]
Discussion:

<details>
<summary>MATF meeting on June 19, 2024</summary>

[Source](https://www.w3.org/2024/06/19-matf-minutes.html#t03)

Quintin: Is an external link along with the content sufficient? Can we include definitions of transcripts and captions? Do captions need to identify speakers and significant sounds?

<Joe_Humbert> Would the definitions be good updates for the larger AG in general?

Quintin: We should focus on the goal

Detlev: What are the different options? What is an author issue?

Quintin: We should mention to respect the OS user settings

JJ: Nothing changes, perhaps add some best practices
</details>

Summary:

1. **External Links for Content:**
    - **Quintin:** Asked whether providing an external link along with the content is sufficient.
  
2. **Definitions of Transcripts and Captions:**
    - **Quintin:** Proposed including definitions for transcripts and captions, and questioned if captions need to identify speakers and significant sounds.
    - **Joe Humbert:** Suggested that the definitions could be beneficial updates for the larger Accessibility Guidelines (AG) in general.
    - **Quintin:** Emphasized focusing on the overall goal.
  
3. **Options and Author Issues:**
    - **Detlev:** Inquired about the different options available and what constitutes an author issue.
    - **Quintin:** Recommended mentioning the importance of respecting the OS user settings.
    - **JJ:** Noted that nothing fundamentally changes, but suggested adding some best practices.

**Comment by julianmka** [comment]
Based on previous task force conversation, this SC can be applied to native mobile apps and mobile web with minimal or no deviation from WCAG2ICT.

### Proposal
In MATF's first draft of guidance, this SC's section will [read as presented in WCAG2ICT](https://www.w3.org/TR/wcag2ict-22/#audio-only-and-video-only-prerecorded) except for wording adjustments that reflect native mobile app and mobile web context.

Please indicate your agreement with a thumbs up emoji, or if you disagree, use the thumbs down emoji and elaborate in comments.

**Comment by julianmka** [comment]
After discussion and voting at the meeting today, the task force members present accepted the proposed language for the first draft of our guidance, minus Note 2 about Closed Functionality.
