### ISSUE TITLE
Success Criterion 1.2.2 - Captions (Prerecorded) - Level A

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#18]
Discussion:

<details>
<summary>MATF meeting on June 19, 2024</summary>

[Source](https://www.w3.org/2024/06/19-matf-minutes.html#t04)

JJ: Already partially discussed

Quintin: We should mention to respect the OS user settings
Quintin: Do captions need to identify speakers and significant sounds?

JJ: Is there a difference or difference in guidance from the Web 1.2.2?

JJ: Mostly on Web captions are not being picked up

Detlev: Players not picking up captions: Is this an app or browsing context?

<JJ> Quitin: Native players provided out-of-the-box on Android/iOS

<JJ> Detlev: so it's mostly guidance for the videoplayer creators vs developers

Agree

JJ: Perhaps provide guidance to facilitate understanding
</details>

Summary:

1. **Respecting OS User Settings:**
    - **Quintin:** Emphasized the importance of mentioning to respect the OS user settings in mobile app development.
  
2. **Identification in Captions:**
    - **Quintin:** Raised the question of whether captions need to identify speakers and significant sounds.
  
3. **Guidance Differences:**
    - **JJ:** Asked if there are differences or specific guidance from Web 1.2.2 regarding caption usage in mobile apps.
    - **Detlev:** Inquired about issues where players do not pick up captions, clarifying if this is in an app or browsing context.
    - **Quintin:** Noted that it's about native players which are provided out-of-the-box on Android/iOS platforms.
    - **Detlev:** Suggested that guidance primarily applies to video player creators rather than developers.
    - **JJ:** Proposed providing guidance to facilitate better understanding in implementing captions effectively.

**Comment by JJdeGroot** [comment]
Related issue: https://github.com/w3c/matf/issues/19

**Comment by julianmka** [comment]
Based on previous task force conversation, this SC can be applied to native mobile apps and mobile web with minimal or no deviation from WCAG2ICT.

Proposal
In MATF's first draft of guidance, this SC's section will [read as presented in WCAG2ICT](https://www.w3.org/TR/wcag2ict-22/#captions-prerecorded) except for wording adjustments that reflect native mobile app and mobile web context.

Please indicate your agreement with a thumbs up emoji 👍, or if you disagree, use the thumbs down emoji 👎 and elaborate in comments.

**Comment by julianmka** [comment]
After discussion and voting at the meeting today, the task force members present accepted the proposed language for the first draft of our guidance.

**Comment by JJdeGroot** [comment]
Closing this issue because the draft language has been accepted.
