### ISSUE TITLE
Success Criterion 1.2.4 - Captions (Live) - Level AA

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#19]
Discussion:

<details>
<summary>MATF meeting on June 19, 2024</summary>

[Source](https://www.w3.org/2024/06/19-matf-minutes.html#t05)

JJ: Any additional understanding on 1.2.4?

Aashutosh: They need to be visible

Quintin: Highlight OS settings should be respected re: size and colours of caption font and background

Quintin: Usually vendors specify the position of captions

JJ: Add this to the application part or recommendations

Alain: EN has extra criteria (7.1.4) and 11.7

Alain: Outside of WCAG to support customization

<AlainVagner> EN 301 549 7.1.4 https://www.etsi.org/deliver/etsi_en/301500_301599/301549/03.02.01_60/en_301549v030201p.pdf#page=35

Detlev: It could be trickier in mobile as there is less space for controls, etc.

JJ: How do we deal with open captions regarding guidance?

Detlev: They are a "get out of jail free" card as you can't change them post processing

JJ: Do open captions comply?

Detlev: It's not ideal, but it's something that could "get past" requirements

Quintin: If someone is using a braille display, open captions won't be helpful

<Audrey> the EN also has a criteria for that : 7.1.5 Spoken subtitles, really interesting for that use case.
</details>

Summary:

1. **Caption Customization:**
    - **Quintin:** Highlighted the importance of respecting OS settings for caption font size and colors, and mentioned that vendors usually specify caption positioning.
    - **JJ:** Suggested adding these considerations to the application part or recommendations.
    - **Alain Vagner:** Referenced EN 301 549 criteria 7.1.4 and 11.7, which support additional customization beyond WCAG standards.
    - **Detlev:** Noted that mobile platforms present challenges due to limited space for controls.
  
2. **Open Captions in Mobile Apps:**
    - **JJ:** Asked how to handle guidance for open captions in mobile apps.
    - **Detlev:** Described open captions as a workaround ("get out of jail free" card) because they cannot be changed post-processing.
    - **JJ:** Questioned if open captions comply with accessibility requirements.
    - **Detlev:** Mentioned that while not ideal, open captions could still meet basic requirements, but they may not be helpful for users with braille displays.
    - **Audrey:** Referenced EN 301 549 criteria 7.1.5 regarding spoken subtitles, highlighting their relevance in certain accessibility use cases.

**Comment by JJdeGroot** [comment]
Related issue: https://github.com/w3c/matf/issues/18

**Comment by julianmka** [comment]
Based on previous task force conversation, this SC can be applied to native mobile apps and mobile web with minimal or no deviation from WCAG2ICT.

Proposal
In MATF's first draft of guidance, this SC's section will [read as presented in WCAG2ICT](https://www.w3.org/TR/wcag2ict-22/#captions-live) except for wording adjustments that reflect native mobile app and mobile web context.

Please indicate your agreement with a thumbs up emoji 👍, or if you disagree, use the thumbs down emoji 👎 and elaborate in comments.

**Comment by julianmka** [comment]
After discussion and voting at the meeting today, the task force members present accepted the proposed language for the first draft of our guidance.

**Comment by JJdeGroot** [comment]
Closing this issue because the draft language has been accepted.
