### ISSUE TITLE
Success Criterion 1.4.2 - Audio Control - Level A

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#27]
<details>
<summary>MATF meeting on July 17, 2024</summary>

[Source](https://www.w3.org/2024/07/17-matf-minutes.html#t03)

<Quintin> Independent from system volume? Super weird

<Mick> I would say we should follow the current WCAG structure - otherwise we could rewrite a lot of the success criteria.

JJ; There is some overlap, but this is under perceivable and focused specifically on audio, as opposed to operable and more general

+1 Mick

<Jamie> +1 to Mick

JJ: What about Splash screens?

<Tori> I see (hear) it on spa and salon websites a lot still in the US

<Tori> Chromium and other browsers have the ability to mute now, but that would fall under UAAG IMO

Jamie: Do we need to discuss this, what do we need to change

Tori: Building on what Jamie said - a lot of these are general - these are the areas that are fairly agnostic

<Jamie> +1 to Tori,, and we need an actionable item from Agendum 2

JJ agrees

I do feel that since phones have a dedicated rocker for volume that it should respect the user settings

Jamie: Can we add action items for agenda 1 + 2 to take ownership for 1.4.1 and 1.4.2?

ACTION: Create subgroup to discuss 1.4.1 and 1.4.2 within the Github repo

<JJ> move to previous agendum
</details>

WCAG2ICT guidance: https://w3c.github.io/wcag2ict/#audio-control

Share your thoughts for applying to mobile apps as a comment below.

**Comment by qbalsdon** [comment]
The only thing I would like to discuss here is why 2.2.2 Pause, Stop, Hide can't cover this criterion? I'm nothing if not redundant, but it seems a bit odd.

**Comment by julianmka** [comment]
Based on previous task force conversation, this SC can be applied to native mobile apps and mobile web with minimal or no deviation from WCAG2ICT.

Proposal
In MATF's first draft of guidance, this SC's section will [read as presented in WCAG2ICT](https://www.w3.org/TR/wcag2ict-22/#audio-control) except for wording adjustments that reflect native mobile app and mobile web context.

Please indicate your agreement with a thumbs up emoji 👍, or if you disagree, use the thumbs down emoji 👎 and elaborate in comments.

**Comment by julianmka** [comment]
After discussion and voting at the meeting today, the task force members present accepted the proposed language for the first draft of our guidance, minus the note on Closed Functionality.

**Comment by JJdeGroot** [comment]
Closing this issue because the draft language has been accepted.
