### ISSUE TITLE
Success Criterion 3.3.1 - Error Identification - Level A

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#44]
WCAG2ICT guidance: https://www.w3.org/TR/wcag2ict-22/#error-identification

Share your thoughts for applying to mobile apps as a comment below.

**Comment by julianmka** [comment]
Based on previous task force conversation, this SC can be applied to native mobile apps and mobile web with minimal or no deviation from WCAG2ICT.

### Proposal
In MATF's first draft of guidance, this SC's section will read as:

>This applies directly as written, and as described in [Intent from Understanding Success Criterion 3.3.1](https://www.w3.org/WAI/WCAG22/Understanding/error-identification#intent).

Please indicate your agreement with a thumbs up emoji 👍, or if you disagree, use the thumbs down emoji 👎 and elaborate in comments.

**Comment by jamieherrera** [comment]
The Intent documentation does mention an error message could be in a dialog rather than on the same page as the error itself. I wonder if we should add a note that dialogs are common for native iOS and Android communication? My company had a conversation about whether dialogs were acceptable; people were getting snagged on the phrase "in text".

**Comment by julianmka** [comment]
I think that would be a good note to add, @jamieherrera, with the caveat that there does need to be some kind of inline indication of the error as well. 

The pattern I usually recommend for screens with multiple validated inputs is to throw an alert dialogue with a more general message about the error(s) and then use an inline message to give details for each input with an error.

**Comment by JJdeGroot** [comment]
Closing this issue because the draft language has been accepted.
