### ISSUE TITLE
Success Criterion 3.3.7 - Redundant Entry - Level A

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#46]
WCAG2ICT guidance: https://www.w3.org/TR/wcag2ict-22/#redundant-entry

Share your thoughts for applying to mobile apps as a comment below.

**Comment by julianmka** [comment]
Based on previous task force conversation, this SC can be applied to native mobile apps and mobile web with minimal or no deviation from WCAG2ICT.

### Proposal
In MATF's first draft of guidance, this SC's section will read as:

>This applies directly as written, and as described in [Intent from Understanding Success Criterion 3.3.7](https://www.w3.org/WAI/WCAG22/Understanding/redundant-entry#intent).

Please indicate your agreement with a thumbs up emoji 👍, or if you disagree, use the thumbs down emoji 👎 and elaborate in comments.

**Comment by JJdeGroot** [comment]
Closing this issue because the draft language has been accepted.
