### ISSUE TITLE
Success Criterion 3.3.4 - Error Prevention (Legal, Financial, Data) - Level AA

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#58]
WCAG2ICT guidance: https://www.w3.org/TR/wcag2ict-22/#error-prevention-legal-financial-data

Share your thoughts for applying to mobile apps as a comment below.

**Comment by julianmka** [comment]
Based on previous task force conversation, this SC can be applied to native mobile apps and mobile web with minimal or no deviation from WCAG2ICT.

### Proposal
In MATF's first draft of guidance, this SC's section will read as:

>This applies directly as written, and as described in [Intent from Understanding Success Criterion 3.3.4](https://www.w3.org/WAI/WCAG22/Understanding/error-prevention-legal-financial-data#intent) replacing “web pages” with “screens or views”.

> 
>With this substitution, it would read:

> 
> 3.3.4 Error Prevention (Legal, Financial, Data): For [screens or views] that cause [legal commitments](https://www.w3.org/TR/WCAG22/#dfn-legal-commitments) or financial transactions for the user to occur, that modify or delete [user-controllable](https://www.w3.org/TR/WCAG22/#dfn-user-controllable) data in data storage systems, or that submit user test responses, at least one of the following is true:

> 
>1. Reversible: Submissions are reversible.
>2. Checked: Data entered by the user is checked for [input errors](https://www.w3.org/TR/wcag2ict-22/#dfn-input-error) and the user is provided an opportunity to correct them.

>3. Confirmed: A [mechanism](https://www.w3.org/TR/WCAG22/#dfn-mechanism) is available for reviewing, confirming, and correcting information before finalizing the submission.

Please indicate your agreement with a thumbs up emoji 👍, or if you disagree, use the thumbs down emoji 👎 and elaborate in comments.

**Comment by JJdeGroot** [comment]
Closing this issue because the draft language has been accepted.
