### ISSUE TITLE
Success Criterion 3.3.7 - Redundant Entry - Level AA

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#59]
WCAG2ICT guidance: https://www.w3.org/TR/wcag2ict-22/#redundant-entry

Share your thoughts for applying to mobile apps as a comment below.

**Comment by julianmka** [comment]
@JJdeGroot, this issue seems to be a duplicate of #46. Could we close this one and keep discussion in #46?

**Comment by julianmka** [comment]
Closing as this issue duplicates #46.
