### ISSUE TITLE
Supporting system settings

### ISSUE THREAD

**Issue by JJdeGroot** [w3c/matf#64]
The requirements of some Success Criteria can be met by supporting system settings.

Examples: 
- High contrast mode for 1.4.3 and 1.4.11
- Extend time of toasts (Android) for 2.2.1 Timing Adjustable
- Reduce motion (iOS), remove animations (Android) for 2.2.2 Stop, Pause, Hide

As discussed in meeting of July 31, general consensus seems to be that apps should also **also** meet WCAG requirements without system settings. E.g. apps should have sufficient contrast without the need to turn on "High contrast mode". However, developers should be encouraged to support system settings for enhanced accessibility.

Share your thoughts for applying to mobile apps as a comment below.

**Comment by AlainVagner** [comment]
In our evaluation method in Luxembourg we only check contrasts with the enhanced contrast mode activated.
By default on iOS at least, it seems that some OS level UI components are not compliant until this mode is activated.

**Comment by JJdeGroot** [comment]
I'm closing this issue in favor of https://github.com/w3c/matf/issues/67 which is a duplicate with more discussion.
